version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./data/database:/app/database
    environment:
      - NODE_ENV=production
      - PORT=5001
      - DB_PATH=/app/database/database.sqlite
    ports:
      - "5001:5001"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

